INSERT INTO Events(disciplineName,eventName) VALUES ('3x3 Basketball','Men');
INSERT INTO Events(disciplineName,eventName) VALUES ('3x3 Basketball','Women');
INSERT INTO Events(disciplineName,eventName) VALUES ('Archery','Men''s Team');
INSERT INTO Events(disciplineName,eventName) VALUES ('Archery','Mixed Team');
INSERT INTO Events(disciplineName,eventName) VALUES ('Archery','Women''s Team');
INSERT INTO Events(disciplineName,eventName) VALUES ('Artistic Gymnastics','Men''s Team');
INSERT INTO Events(disciplineName,eventName) VALUES ('Artistic Gymnastics','Women''s Team');
INSERT INTO Events(disciplineName,eventName) VALUES ('Artistic Swimming','Duet');
INSERT INTO Events(disciplineName,eventName) VALUES ('Artistic Swimming','Team');
INSERT INTO Events(disciplineName,eventName) VALUES ('Athletics','4 x 400m Relay Mixed');
INSERT INTO Events(disciplineName,eventName) VALUES ('Athletics','Men''s 4 x 100m Relay');
INSERT INTO Events(disciplineName,eventName) VALUES ('Athletics','Men''s 4 x 400m Relay');
INSERT INTO Events(disciplineName,eventName) VALUES ('Athletics','Women''s 4 x 100m Relay');
INSERT INTO Events(disciplineName,eventName) VALUES ('Athletics','Women''s 4 x 400m Relay');
INSERT INTO Events(disciplineName,eventName) VALUES ('Baseball/Softball','Baseball');
INSERT INTO Events(disciplineName,eventName) VALUES ('Baseball/Softball','Softball');
INSERT INTO Events(disciplineName,eventName) VALUES ('Basketball','Men');
INSERT INTO Events(disciplineName,eventName) VALUES ('Basketball','Women');
INSERT INTO Events(disciplineName,eventName) VALUES ('Beach Volleyball','Men');
INSERT INTO Events(disciplineName,eventName) VALUES ('Beach Volleyball','Women');
INSERT INTO Events(disciplineName,eventName) VALUES ('Cycling Track','Men''s Madison');
INSERT INTO Events(disciplineName,eventName) VALUES ('Cycling Track','Men''s Team Pursuit');
INSERT INTO Events(disciplineName,eventName) VALUES ('Cycling Track','Men''s Team Sprint');
INSERT INTO Events(disciplineName,eventName) VALUES ('Cycling Track','Women''s Madison');
INSERT INTO Events(disciplineName,eventName) VALUES ('Cycling Track','Women''s Team Pursuit');
INSERT INTO Events(disciplineName,eventName) VALUES ('Cycling Track','Women''s Team Sprint');
INSERT INTO Events(disciplineName,eventName) VALUES ('Fencing','Men''s Epee Team');
INSERT INTO Events(disciplineName,eventName) VALUES ('Fencing','Men''s Foil Team');
INSERT INTO Events(disciplineName,eventName) VALUES ('Fencing','Men''s Sabre Team');
INSERT INTO Events(disciplineName,eventName) VALUES ('Fencing','Women''s Epee Team');
INSERT INTO Events(disciplineName,eventName) VALUES ('Fencing','Women''s Foil Team');
INSERT INTO Events(disciplineName,eventName) VALUES ('Fencing','Women''s Sabre Team');
INSERT INTO Events(disciplineName,eventName) VALUES ('Football','Men');
INSERT INTO Events(disciplineName,eventName) VALUES ('Football','Women');
INSERT INTO Events(disciplineName,eventName) VALUES ('Handball','Men');
INSERT INTO Events(disciplineName,eventName) VALUES ('Handball','Women');
INSERT INTO Events(disciplineName,eventName) VALUES ('Hockey','Men');
INSERT INTO Events(disciplineName,eventName) VALUES ('Hockey','Women');
INSERT INTO Events(disciplineName,eventName) VALUES ('Rhythmic Gymnastics','Group All-Around');
INSERT INTO Events(disciplineName,eventName) VALUES ('Rugby Sevens','Men');
INSERT INTO Events(disciplineName,eventName) VALUES ('Rugby Sevens','Women');
INSERT INTO Events(disciplineName,eventName) VALUES ('Swimming','Men''s 4 x 100m Freestyle Relay');
INSERT INTO Events(disciplineName,eventName) VALUES ('Swimming','Men''s 4 x 100m Medley Relay');
INSERT INTO Events(disciplineName,eventName) VALUES ('Swimming','Men''s 4 x 200m Freestyle Relay');
INSERT INTO Events(disciplineName,eventName) VALUES ('Swimming','Mixed 4 x 100m Medley Relay');
INSERT INTO Events(disciplineName,eventName) VALUES ('Swimming','Women''s 4 x 100m Freestyle Relay');
INSERT INTO Events(disciplineName,eventName) VALUES ('Swimming','Women''s 4 x 100m Medley Relay');
INSERT INTO Events(disciplineName,eventName) VALUES ('Swimming','Women''s 4 x 200m Freestyle Relay');
INSERT INTO Events(disciplineName,eventName) VALUES ('Table Tennis','Men''s Team');
INSERT INTO Events(disciplineName,eventName) VALUES ('Table Tennis','Mixed Doubles');
INSERT INTO Events(disciplineName,eventName) VALUES ('Table Tennis','Women''s Team');
INSERT INTO Events(disciplineName,eventName) VALUES ('Triathlon','Mixed Relay');
INSERT INTO Events(disciplineName,eventName) VALUES ('Volleyball','Men');
INSERT INTO Events(disciplineName,eventName) VALUES ('Volleyball','Women');
INSERT INTO Events(disciplineName,eventName) VALUES ('Water Polo','Men');
INSERT INTO Events(disciplineName,eventName) VALUES ('Water Polo','Women');