INSERT INTO Coaches(coachName,countryName,disciplineName,eventName) VALUES ('ABDELMAGID Wael','Egypt','Football',NULL);
INSERT INTO Coaches(coachName,countryName,disciplineName,eventName) VALUES ('ABE Junya','Japan','Volleyball',NULL);
INSERT INTO Coaches(coachName,countryName,disciplineName,eventName) VALUES ('ABE Katsuhiko','Japan','Basketball',NULL);
INSERT INTO Coaches(coachName,countryName,disciplineName,eventName) VALUES ('ADAMA Cherif','Côte d''Ivoire','Football',NULL);
INSERT INTO Coaches(coachName,countryName,disciplineName,eventName) VALUES ('AGEBA Yuya','Japan','Volleyball',NULL);
INSERT INTO Coaches(coachName,countryName,disciplineName,eventName) VALUES ('AIKMAN Siegfried Gottlieb','Japan','Hockey','Men');
INSERT INTO Coaches(coachName,countryName,disciplineName,eventName) VALUES ('AL SAADI Kais','Germany','Hockey','Men');
INSERT INTO Coaches(coachName,countryName,disciplineName,eventName) VALUES ('ALAMEDA Lonni','Canada','Baseball/Softball','Softball');
INSERT INTO Coaches(coachName,countryName,disciplineName,eventName) VALUES ('ALEKNO Vladimir','Islamic Republic of Iran','Volleyball','Men');
INSERT INTO Coaches(coachName,countryName,disciplineName,eventName) VALUES ('ALEKSEEV Alexey','ROC','Handball','Women');
INSERT INTO Coaches(coachName,countryName,disciplineName,eventName) VALUES ('ALLER CARBALLO Manuel Angel','Spain','Basketball',NULL);
INSERT INTO Coaches(coachName,countryName,disciplineName,eventName) VALUES ('ALSHEHRI Saad','Saudi Arabia','Football','Men');
INSERT INTO Coaches(coachName,countryName,disciplineName,eventName) VALUES ('ALY Kamal','Egypt','Football',NULL);
INSERT INTO Coaches(coachName,countryName,disciplineName,eventName) VALUES ('AMAYA GAITAN Fabian','Puerto Rico','Basketball',NULL);
INSERT INTO Coaches(coachName,countryName,disciplineName,eventName) VALUES ('AMO AGUADO Pablo','Spain','Football',NULL);
INSERT INTO Coaches(coachName,countryName,disciplineName,eventName) VALUES ('ANDONOVSKI Vlatko','United States of America','Football','Women');
INSERT INTO Coaches(coachName,countryName,disciplineName,eventName) VALUES ('ANNAN Alyson','Netherlands','Hockey','Women');
INSERT INTO Coaches(coachName,countryName,disciplineName,eventName) VALUES ('ARNAU CREUS Xavier','Japan','Hockey','Women');
INSERT INTO Coaches(coachName,countryName,disciplineName,eventName) VALUES ('ARNOLD Graham','Australia','Football','Men');
INSERT INTO Coaches(coachName,countryName,disciplineName,eventName) VALUES ('AXNER Tomas','Sweden','Handball','Women');
INSERT INTO Coaches(coachName,countryName,disciplineName,eventName) VALUES ('BABER Gareth Colin','Fiji','Rugby Sevens','Men');
INSERT INTO Coaches(coachName,countryName,disciplineName,eventName) VALUES ('BACIU Horatiu','Romania','Football',NULL);
INSERT INTO Coaches(coachName,countryName,disciplineName,eventName) VALUES ('BANBULA Wojciech','Poland','Volleyball',NULL);
INSERT INTO Coaches(coachName,countryName,disciplineName,eventName) VALUES ('BAO Zhuang','People''s Republic of China','Volleyball',NULL);
INSERT INTO Coaches(coachName,countryName,disciplineName,eventName) VALUES ('BARYLA Pawel','ROC','Volleyball',NULL);
INSERT INTO Coaches(coachName,countryName,disciplineName,eventName) VALUES ('BASILIO Mel','Canada','Baseball/Softball','Softball');
INSERT INTO Coaches(coachName,countryName,disciplineName,eventName) VALUES ('BASSO Paola','Great Britain','Artistic Swimming','Duet');
INSERT INTO Coaches(coachName,countryName,disciplineName,eventName) VALUES ('BATCH Colin','Australia','Hockey','Men');
INSERT INTO Coaches(coachName,countryName,disciplineName,eventName) VALUES ('BATISTA Fernando','Argentina','Football','Men');
INSERT INTO Coaches(coachName,countryName,disciplineName,eventName) VALUES ('BATISTA SANTIAGO Gerardo','Puerto Rico','Basketball','Women');
INSERT INTO Coaches(coachName,countryName,disciplineName,eventName) VALUES ('BENCIC Filip','Serbia','Basketball',NULL);
INSERT INTO Coaches(coachName,countryName,disciplineName,eventName) VALUES ('BERG Laura','United States of America','Baseball/Softball','Softball');
INSERT INTO Coaches(coachName,countryName,disciplineName,eventName) VALUES ('BERGE Christian','Norway','Handball','Men');
INSERT INTO Coaches(coachName,countryName,disciplineName,eventName) VALUES ('BILLAVA SURESH Ankitha','India','Hockey','Women');
INSERT INTO Coaches(coachName,countryName,disciplineName,eventName) VALUES ('BIRO Attila','Hungary','Water Polo','Women');
INSERT INTO Coaches(coachName,countryName,disciplineName,eventName) VALUES ('BLECHER SIDOROVA Svetlana','Israel','Artistic Swimming','Duet');
INSERT INTO Coaches(coachName,countryName,disciplineName,eventName) VALUES ('BLENGINI Gianlorenzo','Italy','Volleyball','Men');
INSERT INTO Coaches(coachName,countryName,disciplineName,eventName) VALUES ('BOLTON Alice','Nigeria','Basketball',NULL);
INSERT INTO Coaches(coachName,countryName,disciplineName,eventName) VALUES ('BREIVIK Marit','Norway','Handball',NULL);
INSERT INTO Coaches(coachName,countryName,disciplineName,eventName) VALUES ('BRODERICK William','Brazil','Rugby Sevens','Women');
INSERT INTO Coaches(coachName,countryName,disciplineName,eventName) VALUES ('BRONDELLO Sandy','Australia','Basketball','Women');
INSERT INTO Coaches(coachName,countryName,disciplineName,eventName) VALUES ('BROWN Chris','United States of America','Rugby Sevens','Women');
INSERT INTO Coaches(coachName,countryName,disciplineName,eventName) VALUES ('BROWN Michael','Nigeria','Basketball','Men');
INSERT INTO Coaches(coachName,countryName,disciplineName,eventName) VALUES ('BRUN Aristide','Austria','Artistic Swimming',NULL);
INSERT INTO Coaches(coachName,countryName,disciplineName,eventName) VALUES ('BUNTING Allan','New Zealand','Rugby Sevens','Women');
INSERT INTO Coaches(coachName,countryName,disciplineName,eventName) VALUES ('BURLANDO Giovanna','Italy','Artistic Swimming',NULL);
INSERT INTO Coaches(coachName,countryName,disciplineName,eventName) VALUES ('BUSATO Sergio','ROC','Volleyball','Women');
INSERT INTO Coaches(coachName,countryName,disciplineName,eventName) VALUES ('BUSENKELL Axel','Germany','Football',NULL);
INSERT INTO Coaches(coachName,countryName,disciplineName,eventName) VALUES ('BYRNE Mick','Canada','Rugby Sevens','Women');
INSERT INTO Coaches(coachName,countryName,disciplineName,eventName) VALUES ('CADENAS MONTANES Manuel','Argentina','Handball','Men');
INSERT INTO Coaches(coachName,countryName,disciplineName,eventName) VALUES ('CALDAS Max','Netherlands','Hockey','Men');
INSERT INTO Coaches(coachName,countryName,disciplineName,eventName) VALUES ('CAMPAGNA Alessandro','Italy','Water Polo','Men');
INSERT INTO Coaches(coachName,countryName,disciplineName,eventName) VALUES ('CARO Carlos','Mexico','Baseball/Softball','Softball');
INSERT INTO Coaches(coachName,countryName,disciplineName,eventName) VALUES ('CASAREZ Mary Lucy','Japan','Baseball/Softball','Softball');
INSERT INTO Coaches(coachName,countryName,disciplineName,eventName) VALUES ('CASTRO Alex','Chile','Football',NULL);
INSERT INTO Coaches(coachName,countryName,disciplineName,eventName) VALUES ('CHAMBERS Cheryl','Australia','Basketball',NULL);
INSERT INTO Coaches(coachName,countryName,disciplineName,eventName) VALUES ('CHEPAK Anastasiya','Egypt','Artistic Swimming','Duet');
INSERT INTO Coaches(coachName,countryName,disciplineName,eventName) VALUES ('CHEPAK Anastasiya','Egypt','Artistic Swimming','Team');
INSERT INTO Coaches(coachName,countryName,disciplineName,eventName) VALUES ('CHERNETSKA Natalia','Greece','Artistic Swimming','Duet');
INSERT INTO Coaches(coachName,countryName,disciplineName,eventName) VALUES ('CHERNETSKA Natalia','Greece','Artistic Swimming','Team');
INSERT INTO Coaches(coachName,countryName,disciplineName,eventName) VALUES ('CHIARI Simona','San Marino','Artistic Swimming',NULL);
INSERT INTO Coaches(coachName,countryName,disciplineName,eventName) VALUES ('CHOI Il Eon','Republic of Korea','Baseball/Softball','Baseball');
INSERT INTO Coaches(coachName,countryName,disciplineName,eventName) VALUES ('CHUN Jooweon','Republic of Korea','Basketball','Women');
INSERT INTO Coaches(coachName,countryName,disciplineName,eventName) VALUES ('CLARK STEPHEN Gregg','India','Hockey','Men');
INSERT INTO Coaches(coachName,countryName,disciplineName,eventName) VALUES ('COLLET Vincent','France','Basketball','Men');
INSERT INTO Coaches(coachName,countryName,disciplineName,eventName) VALUES ('COMMENS Adam','Belgium','Hockey',NULL);
INSERT INTO Coaches(coachName,countryName,disciplineName,eventName) VALUES ('COURTEIX David','France','Rugby Sevens','Women');
INSERT INTO Coaches(coachName,countryName,disciplineName,eventName) VALUES ('CRESPI JAUME Margalida','Colombia','Artistic Swimming',NULL);
INSERT INTO Coaches(coachName,countryName,disciplineName,eventName) VALUES ('CRUZ Filipe','Angola','Handball','Women');
INSERT INTO Coaches(coachName,countryName,disciplineName,eventName) VALUES ('DAL ZOTTO Renan','Brazil','Volleyball','Men');
INSERT INTO Coaches(coachName,countryName,disciplineName,eventName) VALUES ('DANCER Sean','Ireland','Hockey','Women');
INSERT INTO Coaches(coachName,countryName,disciplineName,eventName) VALUES ('DANCHENKO Tatiana','ROC','Artistic Swimming','Duet');
INSERT INTO Coaches(coachName,countryName,disciplineName,eventName) VALUES ('DAVY Jeremy','Australia','Hockey','Women');
INSERT INTO Coaches(coachName,countryName,disciplineName,eventName) VALUES ('DAZA Fabian','Chile','Football',NULL);
INSERT INTO Coaches(coachName,countryName,disciplineName,eventName) VALUES ('DELANEY Mike','New Zealand','Hockey',NULL);
INSERT INTO Coaches(coachName,countryName,disciplineName,eventName) VALUES ('DEMCHENKO Zhanna','Kazakhstan','Artistic Swimming','Duet');
INSERT INTO Coaches(coachName,countryName,disciplineName,eventName) VALUES ('DIAZ FERNANDEZ Jenaro Manuel','Spain','Basketball',NULL);
INSERT INTO Coaches(coachName,countryName,disciplineName,eventName) VALUES ('DIAZ HENRIQUEZ Nestor','Dominican Republic','Basketball',NULL);
INSERT INTO Coaches(coachName,countryName,disciplineName,eventName) VALUES ('DIDENKO Natalia','Spain','Artistic Swimming',NULL);
INSERT INTO Coaches(coachName,countryName,disciplineName,eventName) VALUES ('DOBSON Howard','United States of America','Baseball/Softball','Softball');
INSERT INTO Coaches(coachName,countryName,disciplineName,eventName) VALUES ('DORE Karine','Canada','Artistic Swimming',NULL);
INSERT INTO Coaches(coachName,countryName,disciplineName,eventName) VALUES ('DROBNJAK Dragisa','Slovenia','Basketball',NULL);
INSERT INTO Coaches(coachName,countryName,disciplineName,eventName) VALUES ('DUENAS de GALARZA Jorge','Brazil','Handball','Women');
INSERT INTO Coaches(coachName,countryName,disciplineName,eventName) VALUES ('DURO Fernando','Venezuela','Basketball',NULL);
INSERT INTO Coaches(coachName,countryName,disciplineName,eventName) VALUES ('DYKSTRA Trisha','Australia','Basketball',NULL);
INSERT INTO Coaches(coachName,countryName,disciplineName,eventName) VALUES ('ECHEZURIA Manuel','Venezuela','Basketball',NULL);
INSERT INTO Coaches(coachName,countryName,disciplineName,eventName) VALUES ('EDDY Anthony','Ireland','Rugby Sevens','Men');
INSERT INTO Coaches(coachName,countryName,disciplineName,eventName) VALUES ('EITOKU Atsushi','Japan','Artistic Swimming',NULL);
INSERT INTO Coaches(coachName,countryName,disciplineName,eventName) VALUES ('ELAFANDI Nour','Egypt','Artistic Swimming','Duet');
INSERT INTO Coaches(coachName,countryName,disciplineName,eventName) VALUES ('ELAFANDI Nour','Egypt','Artistic Swimming','Team');
INSERT INTO Coaches(coachName,countryName,disciplineName,eventName) VALUES ('ELEK Gabor','Hungary','Handball','Women');
INSERT INTO Coaches(coachName,countryName,disciplineName,eventName) VALUES ('ENGELLAND Chip','United States of America','Basketball',NULL);
INSERT INTO Coaches(coachName,countryName,disciplineName,eventName) VALUES ('ENQUIST Susan','United States of America','Volleyball',NULL);
INSERT INTO Coaches(coachName,countryName,disciplineName,eventName) VALUES ('ERIKSEN Ken','United States of America','Baseball/Softball','Softball');
INSERT INTO Coaches(coachName,countryName,disciplineName,eventName) VALUES ('EWING Gareth','South Africa','Hockey','Men');
INSERT INTO Coaches(coachName,countryName,disciplineName,eventName) VALUES ('FABRE Julie','France','Artistic Swimming','Duet');
INSERT INTO Coaches(coachName,countryName,disciplineName,eventName) VALUES ('FAHMY LATIF Yasmine','Egypt','Artistic Swimming',NULL);
INSERT INTO Coaches(coachName,countryName,disciplineName,eventName) VALUES ('FALERO Miguel','Honduras','Football','Men');
INSERT INTO Coaches(coachName,countryName,disciplineName,eventName) VALUES ('FARINELLI Roberta','Italy','Artistic Swimming','Duet');
INSERT INTO Coaches(coachName,countryName,disciplineName,eventName) VALUES ('FARINELLI Roberta','Italy','Artistic Swimming','Team');
INSERT INTO Coaches(coachName,countryName,disciplineName,eventName) VALUES ('FATOVIC Elvis','Australia','Water Polo','Men');
INSERT INTO Coaches(coachName,countryName,disciplineName,eventName) VALUES ('FAVAREL Pablo','Venezuela','Basketball',NULL);
INSERT INTO Coaches(coachName,countryName,disciplineName,eventName) VALUES ('FEDIUSHYNA Tetiana','Ukraine','Artistic Swimming',NULL);
INSERT INTO Coaches(coachName,countryName,disciplineName,eventName) VALUES ('FERRARO Hernan','Argentina','Volleyball','Women');
INSERT INTO Coaches(coachName,countryName,disciplineName,eventName) VALUES ('FISH Nathan','Israel','Baseball/Softball','Baseball');
INSERT INTO Coaches(coachName,countryName,disciplineName,eventName) VALUES ('FLOWERS Tairia','United States of America','Baseball/Softball','Softball');
INSERT INTO Coaches(coachName,countryName,disciplineName,eventName) VALUES ('FOIREST Laurent','France','Basketball',NULL);
INSERT INTO Coaches(coachName,countryName,disciplineName,eventName) VALUES ('FORREST Scott','Great Britain','Rugby Sevens','Women');
INSERT INTO Coaches(coachName,countryName,disciplineName,eventName) VALUES ('FRIDAY Mike','United States of America','Rugby Sevens','Men');
INSERT INTO Coaches(coachName,countryName,disciplineName,eventName) VALUES ('FUENTES Andrea','United States of America','Artistic Swimming','Duet');
INSERT INTO Coaches(coachName,countryName,disciplineName,eventName) VALUES ('FUERBRINGER Matthew','United States of America','Volleyball',NULL);
INSERT INTO Coaches(coachName,countryName,disciplineName,eventName) VALUES ('FUJIKI Mayuko','Spain','Artistic Swimming','Duet');
INSERT INTO Coaches(coachName,countryName,disciplineName,eventName) VALUES ('FUJIKI Mayuko','Spain','Artistic Swimming','Team');
INSERT INTO Coaches(coachName,countryName,disciplineName,eventName) VALUES ('FULI Saiasi','Fiji','Rugby Sevens','Women');
INSERT INTO Coaches(coachName,countryName,disciplineName,eventName) VALUES ('GADEMAN Pasha','Canada','Hockey','Men');
INSERT INTO Coaches(coachName,countryName,disciplineName,eventName) VALUES ('GAIDUKOV Aleksandr','ROC','Water Polo','Women');
INSERT INTO Coaches(coachName,countryName,disciplineName,eventName) VALUES ('GARCIA HERRERA Manuel','Dominican Republic','Baseball/Softball','Baseball');
INSERT INTO Coaches(coachName,countryName,disciplineName,eventName) VALUES ('GARCIA Nestor','Dominican Republic','Basketball',NULL);
INSERT INTO Coaches(coachName,countryName,disciplineName,eventName) VALUES ('GARCIA PIZARRO Paula','Colombia','Artistic Swimming','Duet');
INSERT INTO Coaches(coachName,countryName,disciplineName,eventName) VALUES ('GARNIER Valerie','France','Basketball','Women');
INSERT INTO Coaches(coachName,countryName,disciplineName,eventName) VALUES ('GERHARDSSON Peter','Sweden','Football','Women');
INSERT INTO Coaches(coachName,countryName,disciplineName,eventName) VALUES ('GIACOBBE Antonio','Tunisia','Volleyball','Men');
INSERT INTO Coaches(coachName,countryName,disciplineName,eventName) VALUES ('GIALLOMBARDO Patrizia','Italy','Artistic Swimming','Duet');
INSERT INTO Coaches(coachName,countryName,disciplineName,eventName) VALUES ('GIALLOMBARDO Patrizia','Italy','Artistic Swimming','Team');
INSERT INTO Coaches(coachName,countryName,disciplineName,eventName) VALUES ('GILLE Guillaume','France','Handball','Men');
INSERT INTO Coaches(coachName,countryName,disciplineName,eventName) VALUES ('GINZBURG Ronen','Czech Republic','Basketball','Men');
INSERT INTO Coaches(coachName,countryName,disciplineName,eventName) VALUES ('GISLASON Alfred','Germany','Handball','Men');
INSERT INTO Coaches(coachName,countryName,disciplineName,eventName) VALUES ('GOJKOVIC Vladimir','Montenegro','Water Polo','Men');
INSERT INTO Coaches(coachName,countryName,disciplineName,eventName) VALUES ('GOMEZ CORA Santiago','Argentina','Rugby Sevens','Men');
INSERT INTO Coaches(coachName,countryName,disciplineName,eventName) VALUES ('GONZALEZ Anibal','Mexico','Football',NULL);
INSERT INTO Coaches(coachName,countryName,disciplineName,eventName) VALUES ('GONZALEZ JARENO Angel','Spain','Basketball',NULL);
INSERT INTO Coaches(coachName,countryName,disciplineName,eventName) VALUES ('GOORJIAN Brian','Australia','Basketball','Men');
INSERT INTO Coaches(coachName,countryName,disciplineName,eventName) VALUES ('GORDO MANSILLA Juan David','Spain','Football',NULL);
INSERT INTO Coaches(coachName,countryName,disciplineName,eventName) VALUES ('GRAINGER Adam','Ireland','Hockey',NULL);
INSERT INTO Coaches(coachName,countryName,disciplineName,eventName) VALUES ('GRAUPERA Cristina','Greece','Artistic Swimming',NULL);
INSERT INTO Coaches(coachName,countryName,disciplineName,eventName) VALUES ('GRAZIOSI Gianluca','Italy','Volleyball',NULL);
INSERT INTO Coaches(coachName,countryName,disciplineName,eventName) VALUES ('GRESKOWIAK Arne','Germany','Basketball',NULL);
INSERT INTO Coaches(coachName,countryName,disciplineName,eventName) VALUES ('GRYZUNOVA Elena','ROC','Artistic Swimming','Team');
INSERT INTO Coaches(coachName,countryName,disciplineName,eventName) VALUES ('GUERRERO LOPEZ Julen','Spain','Football',NULL);
INSERT INTO Coaches(coachName,countryName,disciplineName,eventName) VALUES ('GUERRERO Rolando','Mexico','Baseball/Softball','Softball');
INSERT INTO Coaches(coachName,countryName,disciplineName,eventName) VALUES ('GUERRERO Rolando','Mexico','Baseball/Softball','Softball');
INSERT INTO Coaches(coachName,countryName,disciplineName,eventName) VALUES ('GUIDETTI Giovanni','Turkey','Volleyball','Women');
INSERT INTO Coaches(coachName,countryName,disciplineName,eventName) VALUES ('GUILLEN Ronald','Venezuela','Basketball',NULL);
INSERT INTO Coaches(coachName,countryName,disciplineName,eventName) VALUES ('GUIMARAES Jose Roberto','Brazil','Volleyball','Women');
INSERT INTO Coaches(coachName,countryName,disciplineName,eventName) VALUES ('GUSTAVSSON Tony','Australia','Football','Women');
INSERT INTO Coaches(coachName,countryName,disciplineName,eventName) VALUES ('HAGER Mark','Great Britain','Hockey','Women');
INSERT INTO Coaches(coachName,countryName,disciplineName,eventName) VALUES ('HAIDARA Soualiho','Côte d''Ivoire','Football','Men');
INSERT INTO Coaches(coachName,countryName,disciplineName,eventName) VALUES ('HALD Simon','Denmark','Handball',NULL);
INSERT INTO Coaches(coachName,countryName,disciplineName,eventName) VALUES ('HALKETT Rhett','Netherlands','Hockey',NULL);
INSERT INTO Coaches(coachName,countryName,disciplineName,eventName) VALUES ('HAM Darvin de','Nigeria','Basketball',NULL);
INSERT INTO Coaches(coachName,countryName,disciplineName,eventName) VALUES ('HARDY William','United States of America','Basketball',NULL);
INSERT INTO Coaches(coachName,countryName,disciplineName,eventName) VALUES ('HARROW Laing','Australia','Baseball/Softball','Softball');
INSERT INTO Coaches(coachName,countryName,disciplineName,eventName) VALUES ('HARVEY Laura','United States of America','Football',NULL);
INSERT INTO Coaches(coachName,countryName,disciplineName,eventName) VALUES ('HAVENGA Arno','Netherlands','Water Polo','Women');
INSERT INTO Coaches(coachName,countryName,disciplineName,eventName) VALUES ('HAY Danny','New Zealand','Football','Men');
INSERT INTO Coaches(coachName,countryName,disciplineName,eventName) VALUES ('HEM Thon Ponloeu','Cambodia','Artistic Swimming',NULL);
INSERT INTO Coaches(coachName,countryName,disciplineName,eventName) VALUES ('HENKEL Claas','Germany','Hockey','Men');
INSERT INTO Coaches(coachName,countryName,disciplineName,eventName) VALUES ('HENNING Andre','Canada','Hockey','Men');
INSERT INTO Coaches(coachName,countryName,disciplineName,eventName) VALUES ('HERGEIRSSON Thorir','Norway','Handball','Women');
INSERT INTO Coaches(coachName,countryName,disciplineName,eventName) VALUES ('HERNANDEZ FRAILE Jose Ignacio','Spain','Basketball',NULL);
INSERT INTO Coaches(coachName,countryName,disciplineName,eventName) VALUES ('HERNANDEZ Sergio','Argentina','Basketball','Men');
INSERT INTO Coaches(coachName,countryName,disciplineName,eventName) VALUES ('HEYNEN Vital','Poland','Volleyball','Men');
INSERT INTO Coaches(coachName,countryName,disciplineName,eventName) VALUES ('HIROSE Norikazu','Japan','Football',NULL);
INSERT INTO Coaches(coachName,countryName,disciplineName,eventName) VALUES ('HOAG Glenn','Canada','Volleyball','Men');
INSERT INTO Coaches(coachName,countryName,disciplineName,eventName) VALUES ('HOLANEK Zoltan','Hungary','Handball',NULL);
INSERT INTO Coaches(coachName,countryName,disciplineName,eventName) VALUES ('HOVASSE Thomas Wayne','Japan','Basketball','Women');
INSERT INTO Coaches(coachName,countryName,disciplineName,eventName) VALUES ('HUGHES Daniel','United States of America','Basketball',NULL);
INSERT INTO Coaches(coachName,countryName,disciplineName,eventName) VALUES ('HUGHLEY JR Otis','Nigeria','Basketball','Women');
INSERT INTO Coaches(coachName,countryName,disciplineName,eventName) VALUES ('IMURA Masayo','Japan','Artistic Swimming',NULL);
INSERT INTO Coaches(coachName,countryName,disciplineName,eventName) VALUES ('IWABUCHI Kensuke','Japan','Rugby Sevens','Men');
INSERT INTO Coaches(coachName,countryName,disciplineName,eventName) VALUES ('JACOBSEN Nikolaj','Denmark','Handball','Men');
INSERT INTO Coaches(coachName,countryName,disciplineName,eventName) VALUES ('JARDINE Andre','Brazil','Football','Men');
INSERT INTO Coaches(coachName,countryName,disciplineName,eventName) VALUES ('JAUMA CAYUELA Esther','Netherlands','Artistic Swimming','Duet');
INSERT INTO Coaches(coachName,countryName,disciplineName,eventName) VALUES ('JENNINGS Dee','Australia','Hockey',NULL);
INSERT INTO Coaches(coachName,countryName,disciplineName,eventName) VALUES ('JEROME Essapa','Côte d''Ivoire','Football',NULL);
INSERT INTO Coaches(coachName,countryName,disciplineName,eventName) VALUES ('JIA Xiuquan','People''s Republic of China','Football','Women');
INSERT INTO Coaches(coachName,countryName,disciplineName,eventName) VALUES ('JIMENEZ NIETO Cecilia','Spain','Artistic Swimming',NULL);
INSERT INTO Coaches(coachName,countryName,disciplineName,eventName) VALUES ('JOHNSON Vickie','United States of America','Basketball',NULL);
INSERT INTO Coaches(coachName,countryName,disciplineName,eventName) VALUES ('JONES Chris','Canada','Baseball/Softball','Softball');
INSERT INTO Coaches(coachName,countryName,disciplineName,eventName) VALUES ('JONES Nathan','Australia','Baseball/Softball','Softball');
INSERT INTO Coaches(coachName,countryName,disciplineName,eventName) VALUES ('KAISER Pierre','Belgium','Basketball',NULL);
INSERT INTO Coaches(coachName,countryName,disciplineName,eventName) VALUES ('KANEKO Makoto','Japan','Baseball/Softball','Baseball');
INSERT INTO Coaches(coachName,countryName,disciplineName,eventName) VALUES ('KANG Jae Won','Republic of Korea','Handball','Women');
INSERT INTO Coaches(coachName,countryName,disciplineName,eventName) VALUES ('KANUNGO Bergin','Zambia','Football',NULL);
INSERT INTO Coaches(coachName,countryName,disciplineName,eventName) VALUES ('KAWASE Asaki','Japan','Football',NULL);
INSERT INTO Coaches(coachName,countryName,disciplineName,eventName) VALUES ('KAZAMA Takafumi','Japan','Football',NULL);
INSERT INTO Coaches(coachName,countryName,disciplineName,eventName) VALUES ('KELLER Florian','Germany','Hockey','Women');
INSERT INTO Coaches(coachName,countryName,disciplineName,eventName) VALUES ('KERRY Danny','Great Britain','Hockey','Men');
INSERT INTO Coaches(coachName,countryName,disciplineName,eventName) VALUES ('KIM Chanbin','Republic of Korea','Football',NULL);
INSERT INTO Coaches(coachName,countryName,disciplineName,eventName) VALUES ('KIM Hagbum','Republic of Korea','Football','Men');
INSERT INTO Coaches(coachName,countryName,disciplineName,eventName) VALUES ('KIRALY Karch','United States of America','Volleyball','Women');
INSERT INTO Coaches(coachName,countryName,disciplineName,eventName) VALUES ('KIRKELY Ulrik','Japan','Handball','Women');
INSERT INTO Coaches(coachName,countryName,disciplineName,eventName) VALUES ('KIRKPATRICK Andrew','Australia','Baseball/Softball','Softball');
INSERT INTO Coaches(coachName,countryName,disciplineName,eventName) VALUES ('KITABAYASHI Kenji','Japan','Handball',NULL);
INSERT INTO Coaches(coachName,countryName,disciplineName,eventName) VALUES ('KLARENBEEK Auke','Netherlands','Handball',NULL);
INSERT INTO Coaches(coachName,countryName,disciplineName,eventName) VALUES ('KNEZEVIC Nemanja','Kazakhstan','Water Polo','Men');
INSERT INTO Coaches(coachName,countryName,disciplineName,eventName) VALUES ('KOFFI Anthony','Côte d''Ivoire','Football',NULL);
INSERT INTO Coaches(coachName,countryName,disciplineName,eventName) VALUES ('KONSTANTINOV Aleksei','ROC','Volleyball',NULL);
INSERT INTO Coaches(coachName,countryName,disciplineName,eventName) VALUES ('KONTIC Svetlana','Serbia','Artistic Swimming',NULL);
INSERT INTO Coaches(coachName,countryName,disciplineName,eventName) VALUES ('KRIKORIAN Adam','United States of America','Water Polo','Women');
INSERT INTO Coaches(coachName,countryName,disciplineName,eventName) VALUES ('KRIST JANSSON Aron','Bahrain','Handball','Men');
INSERT INTO Coaches(coachName,countryName,disciplineName,eventName) VALUES ('KRUMBHOLZ Olivier','France','Handball','Women');
INSERT INTO Coaches(coachName,countryName,disciplineName,eventName) VALUES ('KULESZA Katarzyna','Canada','Artistic Swimming','Team');
INSERT INTO Coaches(coachName,countryName,disciplineName,eventName) VALUES ('KUNTZ Stefan','Germany','Football','Men');
INSERT INTO Coaches(coachName,countryName,disciplineName,eventName) VALUES ('KUZIN Andrey','ROC','Rugby Sevens','Women');
INSERT INTO Coaches(coachName,countryName,disciplineName,eventName) VALUES ('KWIEK Marcos','Dominican Republic','Volleyball','Women');
INSERT INTO Coaches(coachName,countryName,disciplineName,eventName) VALUES ('LAIDLAW Clark','New Zealand','Rugby Sevens','Men');
INSERT INTO Coaches(coachName,countryName,disciplineName,eventName) VALUES ('LAMAS Julio','Japan','Basketball','Men');
INSERT INTO Coaches(coachName,countryName,disciplineName,eventName) VALUES ('LANG Ping','People''s Republic of China','Volleyball','Women');
INSERT INTO Coaches(coachName,countryName,disciplineName,eventName) VALUES ('LAVARINI Stefano','Republic of Korea','Volleyball','Women');
INSERT INTO Coaches(coachName,countryName,disciplineName,eventName) VALUES ('LAZARO CORRAL Jesus','Spain','Basketball',NULL);
INSERT INTO Coaches(coachName,countryName,disciplineName,eventName) VALUES ('LETELIER Jose','Chile','Football','Women');
INSERT INTO Coaches(coachName,countryName,disciplineName,eventName) VALUES ('LOCK Adrian Mayner','Spain','Hockey','Women');
INSERT INTO Coaches(coachName,countryName,disciplineName,eventName) VALUES ('LOFTUS Adriana','Mexico','Artistic Swimming','Duet');
INSERT INTO Coaches(coachName,countryName,disciplineName,eventName) VALUES ('LOPES BARBOSA Leonard','Kenya','Volleyball',NULL);
INSERT INTO Coaches(coachName,countryName,disciplineName,eventName) VALUES ('LOPEZ GUILLEN Melvyn','Dominican Republic','Basketball',NULL);
INSERT INTO Coaches(coachName,countryName,disciplineName,eventName) VALUES ('LOPEZ Monica Susana','Argentina','Artistic Swimming',NULL);
INSERT INTO Coaches(coachName,countryName,disciplineName,eventName) VALUES ('LOUCKS Luke','Nigeria','Basketball',NULL);
INSERT INTO Coaches(coachName,countryName,disciplineName,eventName) VALUES ('LOZANO Jaime','Mexico','Football','Men');
INSERT INTO Coaches(coachName,countryName,disciplineName,eventName) VALUES ('MACEK Anze','Slovenia','Basketball',NULL);
INSERT INTO Coaches(coachName,countryName,disciplineName,eventName) VALUES ('MACKINTOSH Euan Michael Gordon','People''s Republic of China','Rugby Sevens','Women');
INSERT INTO Coaches(coachName,countryName,disciplineName,eventName) VALUES ('MAEDA Kenzo','Japan','Basketball',NULL);
INSERT INTO Coaches(coachName,countryName,disciplineName,eventName) VALUES ('MAHLANGU Sibusiso','South Africa','Football',NULL);
INSERT INTO Coaches(coachName,countryName,disciplineName,eventName) VALUES ('MAKIRI Hare','Japan','Rugby Sevens','Women');
INSERT INTO Coaches(coachName,countryName,disciplineName,eventName) VALUES ('MALJKOVIC Marina','Serbia','Basketball','Women');
INSERT INTO Coaches(coachName,countryName,disciplineName,eventName) VALUES ('MANENTI John','Australia','Rugby Sevens','Women');
INSERT INTO Coaches(coachName,countryName,disciplineName,eventName) VALUES ('MANZANILLO Andres','Venezuela','Volleyball',NULL);
INSERT INTO Coaches(coachName,countryName,disciplineName,eventName) VALUES ('MARCZ Tamas','Hungary','Water Polo','Men');
INSERT INTO Coaches(coachName,countryName,disciplineName,eventName) VALUES ('MARIJNE Sjoerd','India','Hockey','Women');
INSERT INTO Coaches(coachName,countryName,disciplineName,eventName) VALUES ('MARINELLI Fernando','Chile','Football',NULL);
INSERT INTO Coaches(coachName,countryName,disciplineName,eventName) VALUES ('MARTIN LOZANO David','Spain','Water Polo','Men');
INSERT INTO Coaches(coachName,countryName,disciplineName,eventName) VALUES ('MARTIN Paul','South Africa','Water Polo','Men');
INSERT INTO Coaches(coachName,countryName,disciplineName,eventName) VALUES ('MASHA Mario','South Africa','Football',NULL);
INSERT INTO Coaches(coachName,countryName,disciplineName,eventName) VALUES ('MATSUNO Yoshiyuki','Japan','Basketball',NULL);
INSERT INTO Coaches(coachName,countryName,disciplineName,eventName) VALUES ('MATSUODANI Yasushi','Japan','Football',NULL);
INSERT INTO Coaches(coachName,countryName,disciplineName,eventName) VALUES ('MAYBURY Elena','United States of America','Football',NULL);
INSERT INTO Coaches(coachName,countryName,disciplineName,eventName) VALUES ('MAYONNADE Emmanuel','Netherlands','Handball','Women');
INSERT INTO Coaches(coachName,countryName,disciplineName,eventName) VALUES ('MAZZANTI Davide','Italy','Volleyball','Women');
INSERT INTO Coaches(coachName,countryName,disciplineName,eventName) VALUES ('MEDINA Bobby','Nigeria','Basketball',NULL);
INSERT INTO Coaches(coachName,countryName,disciplineName,eventName) VALUES ('MENDEZ Marcelo Rodolfo','Argentina','Volleyball','Men');
INSERT INTO Coaches(coachName,countryName,disciplineName,eventName) VALUES ('MENGUAL CIVIL Gemma','Spain','Artistic Swimming',NULL);
INSERT INTO Coaches(coachName,countryName,disciplineName,eventName) VALUES ('MENTOOR Delaine','South Africa','Water Polo','Women');
INSERT INTO Coaches(coachName,countryName,disciplineName,eventName) VALUES ('MERCEDES del ROSARIO Jose','Dominican Republic','Basketball',NULL);
INSERT INTO Coaches(coachName,countryName,disciplineName,eventName) VALUES ('MESTDAGH Philip','Belgium','Basketball','Women');
INSERT INTO Coaches(coachName,countryName,disciplineName,eventName) VALUES ('MEZHENINA Valeriia','Ukraine','Artistic Swimming','Team');
INSERT INTO Coaches(coachName,countryName,disciplineName,eventName) VALUES ('MEZIANE Rachid','France','Basketball',NULL);
INSERT INTO Coaches(coachName,countryName,disciplineName,eventName) VALUES ('MIHAILOVIC Predrag','Australia','Water Polo','Women');
INSERT INTO Coaches(coachName,countryName,disciplineName,eventName) VALUES ('MIREJOVSKY Michal','Czech Republic','Basketball',NULL);
INSERT INTO Coaches(coachName,countryName,disciplineName,eventName) VALUES ('MIRET GARCIA Daniel','Spain','Basketball',NULL);
INSERT INTO Coaches(coachName,countryName,disciplineName,eventName) VALUES ('MIURA Keiko','Japan','Hockey','Women');
INSERT INTO Coaches(coachName,countryName,disciplineName,eventName) VALUES ('MIYAKAWA Miya','Japan','Artistic Swimming',NULL);
INSERT INTO Coaches(coachName,countryName,disciplineName,eventName) VALUES ('MLADENOVA Albena','Austria','Artistic Swimming','Duet');
INSERT INTO Coaches(coachName,countryName,disciplineName,eventName) VALUES ('MOHAMED Mai','Egypt','Artistic Swimming',NULL);
INSERT INTO Coaches(coachName,countryName,disciplineName,eventName) VALUES ('MOHAMED Sayeda','Saudi Arabia','Football',NULL);
INSERT INTO Coaches(coachName,countryName,disciplineName,eventName) VALUES ('MOHAMMED Silifat','Nigeria','Basketball',NULL);
INSERT INTO Coaches(coachName,countryName,disciplineName,eventName) VALUES ('MONDELO GARCIA Lucas','Spain','Basketball','Women');
INSERT INTO Coaches(coachName,countryName,disciplineName,eventName) VALUES ('MONTICO Loredana','Australia','Artistic Swimming','Duet');
INSERT INTO Coaches(coachName,countryName,disciplineName,eventName) VALUES ('MONTICO Loredana','Australia','Artistic Swimming','Team');
INSERT INTO Coaches(coachName,countryName,disciplineName,eventName) VALUES ('MORIYASU Hajime','Japan','Football','Men');
INSERT INTO Coaches(coachName,countryName,disciplineName,eventName) VALUES ('MOTOMIYA Makihiro','Japan','Water Polo','Women');
INSERT INTO Coaches(coachName,countryName,disciplineName,eventName) VALUES ('MULATI Adilijiang','People''s Republic of China','Basketball',NULL);
INSERT INTO Coaches(coachName,countryName,disciplineName,eventName) VALUES ('MUNOZ Noe de Jesus','Mexico','Baseball/Softball','Baseball');
INSERT INTO Coaches(coachName,countryName,disciplineName,eventName) VALUES ('MWAPE Bruce','Zambia','Football','Women');
INSERT INTO Coaches(coachName,countryName,disciplineName,eventName) VALUES ('McCRORIE Christy','South Africa','Hockey',NULL);
INSERT INTO Coaches(coachName,countryName,disciplineName,eventName) VALUES ('McLEOD Shane','Belgium','Hockey','Men');
INSERT INTO Coaches(coachName,countryName,disciplineName,eventName) VALUES ('NAGAE Shoji','Japan','Volleyball',NULL);
INSERT INTO Coaches(coachName,countryName,disciplineName,eventName) VALUES ('NAIDOO Taren','South Africa','Hockey','Women');
INSERT INTO Coaches(coachName,countryName,disciplineName,eventName) VALUES ('NAKADA Kumi','Japan','Volleyball','Women');
INSERT INTO Coaches(coachName,countryName,disciplineName,eventName) VALUES ('NAKAGAICHI Yuichi','Japan','Volleyball','Men');
INSERT INTO Coaches(coachName,countryName,disciplineName,eventName) VALUES ('NCUBE Mthandazo','South Africa','Football',NULL);
INSERT INTO Coaches(coachName,countryName,disciplineName,eventName) VALUES ('NEVES Christophe','Côte d''Ivoire','Football',NULL);
INSERT INTO Coaches(coachName,countryName,disciplineName,eventName) VALUES ('NISHIDA Takumi','Japan','Rugby Sevens',NULL);
INSERT INTO Coaches(coachName,countryName,disciplineName,eventName) VALUES ('NOTOANE David','South Africa','Football','Men');
INSERT INTO Coaches(coachName,countryName,disciplineName,eventName) VALUES ('OCA GAIA Miguel Angel','Spain','Water Polo','Women');
INSERT INTO Coaches(coachName,countryName,disciplineName,eventName) VALUES ('ODAUDU Ogoh','Nigeria','Basketball',NULL);
INSERT INTO Coaches(coachName,countryName,disciplineName,eventName) VALUES ('OLOO Felix','Kenya','Rugby Sevens','Women');
INSERT INTO Coaches(coachName,countryName,disciplineName,eventName) VALUES ('OMOTO Yoji','Japan','Water Polo','Men');
INSERT INTO Coaches(coachName,countryName,disciplineName,eventName) VALUES ('PAGAN CRISTOBAL Angel','Puerto Rico','Basketball',NULL);
INSERT INTO Coaches(coachName,countryName,disciplineName,eventName) VALUES ('PALERMI Giovanna','Italy','Baseball/Softball','Softball');
INSERT INTO Coaches(coachName,countryName,disciplineName,eventName) VALUES ('PANTOJA Hernan','Venezuela','Volleyball',NULL);
INSERT INTO Coaches(coachName,countryName,disciplineName,eventName) VALUES ('PARADELO David','Canada','Water Polo','Women');
INSERT INTO Coaches(coachName,countryName,disciplineName,eventName) VALUES ('PARRONDO Roberto','Egypt','Handball','Men');
INSERT INTO Coaches(coachName,countryName,disciplineName,eventName) VALUES ('PAUL Henry','Canada','Rugby Sevens','Men');
INSERT INTO Coaches(coachName,countryName,disciplineName,eventName) VALUES ('PECCI Isabella','San Marino','Artistic Swimming',NULL);
INSERT INTO Coaches(coachName,countryName,disciplineName,eventName) VALUES ('PEDRERO Ofelia','Mexico','Artistic Swimming','Duet');
INSERT INTO Coaches(coachName,countryName,disciplineName,eventName) VALUES ('PEREIRA Paulo Jorge','Portugal','Handball','Men');
INSERT INTO Coaches(coachName,countryName,disciplineName,eventName) VALUES ('PEREZ Jose','Venezuela','Basketball',NULL);
INSERT INTO Coaches(coachName,countryName,disciplineName,eventName) VALUES ('PIBIRI Rossella','Italy','Artistic Swimming',NULL);
INSERT INTO Coaches(coachName,countryName,disciplineName,eventName) VALUES ('PISKAREVA Ekaterina','ROC','Artistic Swimming',NULL);
INSERT INTO Coaches(coachName,countryName,disciplineName,eventName) VALUES ('PIZZOLINI Federico','Italy','Baseball/Softball','Softball');
INSERT INTO Coaches(coachName,countryName,disciplineName,eventName) VALUES ('POPOVICH Gregg','United States of America','Basketball','Men');
INSERT INTO Coaches(coachName,countryName,disciplineName,eventName) VALUES ('POROBIC Petar','People''s Republic of China','Water Polo','Women');
INSERT INTO Coaches(coachName,countryName,disciplineName,eventName) VALUES ('POTTER Anthony','Australia','Hockey','Men');
INSERT INTO Coaches(coachName,countryName,disciplineName,eventName) VALUES ('POWELL Katrina','Australia','Hockey','Women');
INSERT INTO Coaches(coachName,countryName,disciplineName,eventName) VALUES ('POWELL Neil','South Africa','Rugby Sevens','Men');
INSERT INTO Coaches(coachName,countryName,disciplineName,eventName) VALUES ('PRADO BRANAS Joaquin','Spain','Basketball',NULL);
INSERT INTO Coaches(coachName,countryName,disciplineName,eventName) VALUES ('PRIESTMAN Bev','Canada','Football','Women');
INSERT INTO Coaches(coachName,countryName,disciplineName,eventName) VALUES ('RADOI Mirel','Romania','Football','Men');
INSERT INTO Coaches(coachName,countryName,disciplineName,eventName) VALUES ('RECKINGER Xavier','Germany','Hockey','Women');
INSERT INTO Coaches(coachName,countryName,disciplineName,eventName) VALUES ('REID Graham John','India','Hockey','Men');
INSERT INTO Coaches(coachName,countryName,disciplineName,eventName) VALUES ('REQUENA PERICAS Judit','Spain','Artistic Swimming','Duet');
INSERT INTO Coaches(coachName,countryName,disciplineName,eventName) VALUES ('REQUENA PERICAS Judit','Spain','Artistic Swimming','Team');
INSERT INTO Coaches(coachName,countryName,disciplineName,eventName) VALUES ('RETEGUI Carlos Jose','Argentina','Hockey','Men');
INSERT INTO Coaches(coachName,countryName,disciplineName,eventName) VALUES ('RETEGUI Carlos Jose','Argentina','Hockey','Women');
INSERT INTO Coaches(coachName,countryName,disciplineName,eventName) VALUES ('RIBERA ROMANS Jordi','Spain','Handball','Men');
INSERT INTO Coaches(coachName,countryName,disciplineName,eventName) VALUES ('RIISE Hege','Great Britain','Football','Women');
INSERT INTO Coaches(coachName,countryName,disciplineName,eventName) VALUES ('RILLIE John','Australia','Basketball',NULL);
INSERT INTO Coaches(coachName,countryName,disciplineName,eventName) VALUES ('RIPOLL Sylvain','France','Football','Men');
INSERT INTO Coaches(coachName,countryName,disciplineName,eventName) VALUES ('RODRIGUEZ Eduardo Rafael','Argentina','Volleyball',NULL);
INSERT INTO Coaches(coachName,countryName,disciplineName,eventName) VALUES ('ROEDL Henrik','Germany','Basketball','Men');
INSERT INTO Coaches(coachName,countryName,disciplineName,eventName) VALUES ('ROQUES Anthony','Great Britain','Rugby Sevens','Men');
INSERT INTO Coaches(coachName,countryName,disciplineName,eventName) VALUES ('SACCHETTI Romeo','Italy','Basketball','Men');
INSERT INTO Coaches(coachName,countryName,disciplineName,eventName) VALUES ('SALAM Mohamed','Egypt','Football',NULL);
INSERT INTO Coaches(coachName,countryName,disciplineName,eventName) VALUES ('SAMMELVUO Tuomas','ROC','Volleyball','Men');
INSERT INTO Coaches(coachName,countryName,disciplineName,eventName) VALUES ('SARTI Ronald','Venezuela','Volleyball','Men');
INSERT INTO Coaches(coachName,countryName,disciplineName,eventName) VALUES ('SAVIC Dejan','Serbia','Water Polo','Men');
INSERT INTO Coaches(coachName,countryName,disciplineName,eventName) VALUES ('SAVIC Maja','Montenegro','Handball','Women');
INSERT INTO Coaches(coachName,countryName,disciplineName,eventName) VALUES ('SCARIOLO Sergio','Spain','Basketball','Men');
INSERT INTO Coaches(coachName,countryName,disciplineName,eventName) VALUES ('SCHILLING April','Nigeria','Basketball',NULL);
INSERT INTO Coaches(coachName,countryName,disciplineName,eventName) VALUES ('SEKULIC Aleksander','Slovenia','Basketball','Men');
INSERT INTO Coaches(coachName,countryName,disciplineName,eventName) VALUES ('SEO Chun Oh','Republic of Korea','Rugby Sevens','Men');
INSERT INTO Coaches(coachName,countryName,disciplineName,eventName) VALUES ('SERMANNI Tom','New Zealand','Football','Women');
INSERT INTO Coaches(coachName,countryName,disciplineName,eventName) VALUES ('SHAHINTAB Mehran','Islamic Republic of Iran','Basketball','Men');
INSERT INTO Coaches(coachName,countryName,disciplineName,eventName) VALUES ('SHAHNAZI Shahbaz','Austria','Artistic Swimming',NULL);
INSERT INTO Coaches(coachName,countryName,disciplineName,eventName) VALUES ('SHAW Graham','New Zealand','Hockey','Women');
INSERT INTO Coaches(coachName,countryName,disciplineName,eventName) VALUES ('SHAWKY Gharib','Egypt','Football','Men');
INSERT INTO Coaches(coachName,countryName,disciplineName,eventName) VALUES ('SIAM Zaghloul','Egypt','Football',NULL);
INSERT INTO Coaches(coachName,countryName,disciplineName,eventName) VALUES ('SIGURDSSON Dagur','Japan','Handball','Men');
INSERT INTO Coaches(coachName,countryName,disciplineName,eventName) VALUES ('SIMIYU Innocent','Kenya','Rugby Sevens','Men');
INSERT INTO Coaches(coachName,countryName,disciplineName,eventName) VALUES ('SINGH Shivendra','India','Hockey','Men');
INSERT INTO Coaches(coachName,countryName,disciplineName,eventName) VALUES ('SMITH Darren','New Zealand','Hockey','Men');
INSERT INTO Coaches(coachName,countryName,disciplineName,eventName) VALUES ('SMITH Mark','Canada','Baseball/Softball','Softball');
INSERT INTO Coaches(coachName,countryName,disciplineName,eventName) VALUES ('SOLBERG Glenn','Sweden','Handball','Men');
INSERT INTO Coaches(coachName,countryName,disciplineName,eventName) VALUES ('SOYEZ Frederic','Spain','Hockey','Men');
INSERT INTO Coaches(coachName,countryName,disciplineName,eventName) VALUES ('SPERAW John','United States of America','Volleyball','Men');
INSERT INTO Coaches(coachName,countryName,disciplineName,eventName) VALUES ('SPERONI Stefania','Great Britain','Artistic Swimming','Duet');
INSERT INTO Coaches(coachName,countryName,disciplineName,eventName) VALUES ('STALEY Dawn','United States of America','Basketball','Women');
INSERT INTO Coaches(coachName,countryName,disciplineName,eventName) VALUES ('STANIFORTH Dave','Australia','Hockey',NULL);
INSERT INTO Coaches(coachName,countryName,disciplineName,eventName) VALUES ('STAS Jacques','Belgium','Basketball',NULL);
INSERT INTO Coaches(coachName,countryName,disciplineName,eventName) VALUES ('SUNDHAGE Pia Mariane','Brazil','Football','Women');
INSERT INTO Coaches(coachName,countryName,disciplineName,eventName) VALUES ('SVETLICHNAYA Aliona','Belarus','Artistic Swimming','Duet');
INSERT INTO Coaches(coachName,countryName,disciplineName,eventName) VALUES ('SZAUDER Gabor','Canada','Artistic Swimming','Duet');
INSERT INTO Coaches(coachName,countryName,disciplineName,eventName) VALUES ('SZAUDER Gabor','Canada','Artistic Swimming','Team');
INSERT INTO Coaches(coachName,countryName,disciplineName,eventName) VALUES ('SZAUDER Nora','Slovakia','Artistic Swimming',NULL);
INSERT INTO Coaches(coachName,countryName,disciplineName,eventName) VALUES ('TAGLE German','Chile','Football',NULL);
INSERT INTO Coaches(coachName,countryName,disciplineName,eventName) VALUES ('TAKAKURA Asako','Japan','Football','Women');
INSERT INTO Coaches(coachName,countryName,disciplineName,eventName) VALUES ('TAKITA Risako','Japan','Artistic Swimming',NULL);
INSERT INTO Coaches(coachName,countryName,disciplineName,eventName) VALUES ('TARR Heather','United States of America','Baseball/Softball','Softball');
INSERT INTO Coaches(coachName,countryName,disciplineName,eventName) VALUES ('TARRES CAMPA Ana','Greece','Artistic Swimming','Duet');
INSERT INTO Coaches(coachName,countryName,disciplineName,eventName) VALUES ('TARRES CAMPA Ana','Greece','Artistic Swimming','Team');
INSERT INTO Coaches(coachName,countryName,disciplineName,eventName) VALUES ('TERZIC Zoran','Serbia','Volleyball','Women');
INSERT INTO Coaches(coachName,countryName,disciplineName,eventName) VALUES ('THOMAIDIS Lisa','Canada','Basketball','Women');
INSERT INTO Coaches(coachName,countryName,disciplineName,eventName) VALUES ('TILLIE Laurent','France','Volleyball','Men');
INSERT INTO Coaches(coachName,countryName,disciplineName,eventName) VALUES ('TOMOMATSU Yumiko','Italy','Artistic Swimming',NULL);
INSERT INTO Coaches(coachName,countryName,disciplineName,eventName) VALUES ('TUCAK Ivica','Croatia','Water Polo','Men');
INSERT INTO Coaches(coachName,countryName,disciplineName,eventName) VALUES ('TURNER Glenn','New Zealand','Hockey','Men');
INSERT INTO Coaches(coachName,countryName,disciplineName,eventName) VALUES ('UDOKA Ime','United States of America','Basketball',NULL);
INSERT INTO Coaches(coachName,countryName,disciplineName,eventName) VALUES ('UDOVICIC Dejan','United States of America','Water Polo','Men');
INSERT INTO Coaches(coachName,countryName,disciplineName,eventName) VALUES ('UTKIN Volodymyr','Ukraine','Artistic Swimming',NULL);
INSERT INTO Coaches(coachName,countryName,disciplineName,eventName) VALUES ('UTSUGI Reika','Japan','Baseball/Softball','Softball');
INSERT INTO Coaches(coachName,countryName,disciplineName,eventName) VALUES ('VASQUEZ Diego','Venezuela','Basketball',NULL);
INSERT INTO Coaches(coachName,countryName,disciplineName,eventName) VALUES ('VEGA HERRERO Anna','Spain','Artistic Swimming',NULL);
INSERT INTO Coaches(coachName,countryName,disciplineName,eventName) VALUES ('VILLEGAS Orlando','Venezuela','Volleyball',NULL);
INSERT INTO Coaches(coachName,countryName,disciplineName,eventName) VALUES ('VITORINO de SOUZA Marcelo','Kenya','Volleyball',NULL);
INSERT INTO Coaches(coachName,countryName,disciplineName,eventName) VALUES ('VIVER ARZA Carlos Enrique','Spain','Handball','Women');
INSERT INTO Coaches(coachName,countryName,disciplineName,eventName) VALUES ('VLACHOS Theodoros','Greece','Water Polo','Men');
INSERT INTO Coaches(coachName,countryName,disciplineName,eventName) VALUES ('VORONOVA Elena','ROC','Artistic Swimming','Duet');
INSERT INTO Coaches(coachName,countryName,disciplineName,eventName) VALUES ('WALL Michael','United States of America','Volleyball',NULL);
INSERT INTO Coaches(coachName,countryName,disciplineName,eventName) VALUES ('WALSH Tim','Australia','Rugby Sevens','Men');
INSERT INTO Coaches(coachName,countryName,disciplineName,eventName) VALUES ('WANG Jie','People''s Republic of China','Artistic Swimming','Duet');
INSERT INTO Coaches(coachName,countryName,disciplineName,eventName) VALUES ('WANG Jie','People''s Republic of China','Artistic Swimming','Team');
INSERT INTO Coaches(coachName,countryName,disciplineName,eventName) VALUES ('WANG Yang','People''s Republic of China','Hockey','Women');
INSERT INTO Coaches(coachName,countryName,disciplineName,eventName) VALUES ('WEINSTEIN Jerry','United States of America','Baseball/Softball','Baseball');
INSERT INTO Coaches(coachName,countryName,disciplineName,eventName) VALUES ('WIEGMAN Sarina','Netherlands','Football','Women');
INSERT INTO Coaches(coachName,countryName,disciplineName,eventName) VALUES ('WIRTH Oscar','Chile','Football',NULL);
INSERT INTO Coaches(coachName,countryName,disciplineName,eventName) VALUES ('WOELFLIN Roberto Osvaldo','Argentina','Volleyball',NULL);
INSERT INTO Coaches(coachName,countryName,disciplineName,eventName) VALUES ('WOICKI Pawel','Poland','Volleyball',NULL);
INSERT INTO Coaches(coachName,countryName,disciplineName,eventName) VALUES ('WRIGHT Jerold','United States of America','Basketball',NULL);
INSERT INTO Coaches(coachName,countryName,disciplineName,eventName) VALUES ('XU Limin','People''s Republic of China','Basketball','Women');
INSERT INTO Coaches(coachName,countryName,disciplineName,eventName) VALUES ('YAMAJI Noriko','Japan','Baseball/Softball','Softball');
INSERT INTO Coaches(coachName,countryName,disciplineName,eventName) VALUES ('YUAN Lingxi','People''s Republic of China','Volleyball',NULL);
INSERT INTO Coaches(coachName,countryName,disciplineName,eventName) VALUES ('YURKIN Sergey','ROC','Volleyball',NULL);
INSERT INTO Coaches(coachName,countryName,disciplineName,eventName) VALUES ('ZAITSEVA Olesia','Ukraine','Artistic Swimming','Duet');
INSERT INTO Coaches(coachName,countryName,disciplineName,eventName) VALUES ('ZAMORA PEDREIRA Javier','Spain','Basketball',NULL);
INSERT INTO Coaches(coachName,countryName,disciplineName,eventName) VALUES ('ZAMPIERI Francesca','Liechtenstein','Artistic Swimming','Duet');
INSERT INTO Coaches(coachName,countryName,disciplineName,eventName) VALUES ('ZHANG Xiaohuan','People''s Republic of China','Artistic Swimming',NULL);
INSERT INTO Coaches(coachName,countryName,disciplineName,eventName) VALUES ('ZIJP Simon','Netherlands','Hockey',NULL);
INSERT INTO Coaches(coachName,countryName,disciplineName,eventName) VALUES ('ZONDI Nkuliso','South Africa','Hockey','Women');
INSERT INTO Coaches(coachName,countryName,disciplineName,eventName) VALUES ('de MOURA Luizomar','Kenya','Volleyball','Women');
INSERT INTO Coaches(coachName,countryName,disciplineName,eventName) VALUES ('de OLIVEIRA Marcus Ricardo','Brazil','Handball','Men');
INSERT INTO Coaches(coachName,countryName,disciplineName,eventName) VALUES ('de VOS Robbert-Jan','Netherlands','Hockey',NULL);
INSERT INTO Coaches(coachName,countryName,disciplineName,eventName) VALUES ('de la FUENTE CASTILLO Luis','Spain','Football','Men');
INSERT INTO Coaches(coachName,countryName,disciplineName,eventName) VALUES ('van GINKEL Robin','South Africa','Hockey','Women');
INSERT INTO Coaches(coachName,countryName,disciplineName,eventName) VALUES ('van GUNDY Jeff','United States of America','Basketball',NULL);